dev/routing ✨
shmlkv/airbnb-demo-frontend pull request #2
Opened 2018-01-11 08:32 UTC by shmlkv

Routing + layout of Home page

2018-01-11 20:20 UTC, evgenyrodionov commented
Чё с иконкой?
![image](https://user-images.githubusercontent.com/775692/34845337-96e25742-f725-11e7-9627-98f4fa59084b.png)

---

Чё со шрифтами у фильтра и с цветами бордера?
![image](https://user-images.githubusercontent.com/775692/34845463-f764805e-f725-11e7-8c95-a5ec51b74d74.png)

2018-01-11 20:21 UTC, evgenyrodionov commented
Да и в футере на этой странице тоже слишком тонкие шрифты

у кнопок нет `cursor: pointer`

2018-01-11 20:39 UTC, imevro requested changes

2018-01-11 20:39 UTC, evgenyrodionov commented on src/Header/Search/index.js
> +export default ({ searchPlaceHolder, ...props }) => {
а нах тебе `props`? лишнее же

2018-01-11 20:39 UTC, evgenyrodionov commented on src/Homes/Filters/Buttons/Guests.js
> +import { Filter } from "../index";
а зачем ты импортишь из индекс? некрасиво

2018-01-11 20:39 UTC, evgenyrodionov commented on src/Homes/Filters/index.js
> +import Dates from "./Buttons/Dates";
а зачем директория баттонс?

2018-01-11 20:39 UTC, evgenyrodionov commented on src/Homes/Filters/index.js
> +  -fx-faint-focus-color: transparent;
это чё вообще такое

2018-01-11 20:39 UTC, evgenyrodionov commented on src/Homes/index.js
> +            <Card className="col-lg-6 col-xs-12 col-sm-6" home={home} />
от меньшего к большему (xs / sm / lg)

2018-01-11 20:39 UTC, evgenyrodionov commented on src/Homes/index.js
> +      <Header searchPlaceHolder="Anywhere · Homes" />
поч не просто placeholder?

2018-01-11 20:39 UTC, evgenyrodionov commented on src/Landing/Explore/index.js
> +  { title: "Homes", image: "Homes.png", link: "/homes" },
ты думаешь ссылки будут с апи переходить, если роутинг на клиенте?)

2018-01-11 20:41 UTC, shmlkv commented on src/Homes/Filters/index.js
> +  -fx-faint-focus-color: transparent;
Чтобы не было синего фокуса в хроме при клике

2018-01-13 08:42 UTC, evgenyrodionov commented
Шрифты
![image](https://user-images.githubusercontent.com/775692/34904426-c0d239f0-f856-11e7-90d2-6552ab42f962.png)
![image](https://user-images.githubusercontent.com/775692/34904427-c36e5c98-f856-11e7-8fca-f8808ccae841.png)

2018-01-13 08:42 UTC, evgenyrodionov commented
А где кнопки сохранить и отмена?
![image](https://user-images.githubusercontent.com/775692/34904431-d33f7440-f856-11e7-9b3d-83cf74899f06.png)

2018-01-13 08:50 UTC, imevro requested changes

2018-01-13 08:50 UTC, evgenyrodionov commented on src/App.css
> +  font-family: "CircularAir-Normal";
самому удобно?) Назови `Circular Air Normal` вместо этой чехарды

2018-01-13 08:50 UTC, evgenyrodionov commented on src/Homes/Filters/DatePicker.js
> +import CloseButton from "./Close.png";
1) это компонент? почему тогда `PascalCase`? 
2) почему иконка в пнг, а не свг?

2018-01-13 08:50 UTC, evgenyrodionov commented on src/Homes/Filters/DatePicker.js
> +const DropdownWindow = onClickOutside(styled.div`
лучше не вешать HoC на ск

2018-01-13 08:50 UTC, evgenyrodionov commented on src/Homes/Filters/DatePicker.js
> +      let end = endDate ? endDate.format("MMM Do") : "Check out";
1) нахуй мутабельность и все эти леты
2) вынеси за пределы класса — я написал об этом в частых ошибках

2018-01-13 08:50 UTC, evgenyrodionov commented on src/Homes/Filters/DatePicker.js
> +  matchMobile = () => {
зачем это методом класса, если можно просто в рендере хранить `const matchedXs = ...`? ну и у нас нет терминологии мобайл/планшет/десктоп, есть xs/sm/md/lg/xl

2018-01-13 08:50 UTC, evgenyrodionov commented on src/Homes/Filters/DatePicker.js
> +    if (window.matchMedia("(max-width: 450px)").matches) return true;
а что мешало сделать `return window.matchMedia...`? возвращает же тот же тру/фолс

ну и проверь поддержку на caniuse

2018-01-13 08:50 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +import "react-dates/lib/css/_datepicker.css";
стили реакт-дейтс буду важнее чем твои

2018-01-13 08:50 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +import "./_datepicker.css";
нахуя _?

2018-01-13 08:50 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +    this.props.onApply(
сетстейт асинхронный, поэтому у тебя туда попадут старые данные. используй коллбек сетстейта чтобы отправить данные 

https://medium.learnreact.com/setstate-takes-a-callback-1f71ad5d2296

2018-01-13 08:50 UTC, evgenyrodionov commented on src/Homes/Filters/_datepicker.css
> +@media (max-width: 450px) {
ставь переносы между блоками кода, ну тяжело же читать без этого

и max-width не используем

2018-01-13 08:50 UTC, evgenyrodionov commented on src/Homes/Filters/index.js
> +    dropdown: null
а если оно станет не дропдауном, а модалами, чё делать будешь?

2018-01-13 08:50 UTC, evgenyrodionov commented on src/Homes/Filters/index.js
> +    dropdown: null
зачем привязываться к реализации

2018-01-13 17:22 UTC, shmlkv commented
https://build-kjxvdqzoli.now.sh/Homes

2018-01-13 17:53 UTC, shmlkv commented
https://build-mduuujcmgo.now.sh/Homes

2018-01-13 18:15 UTC, shmlkv commented
https://build-ijnkxvihmk.now.sh/

2018-01-21 00:00 UTC, imevro requested changes

2018-01-21 00:00 UTC, evgenyrodionov commented on src/Homes/Filters/DatePicker.js
> +const buttonDate = (start, end, selected) => {
если это функция (реально функция), то она должна быть с глаголом

`formatDate`, `formatDateLabel`, етц

Кстати, `selected` → `isSelected`, тогда будет понятно что это булеан

2018-01-21 00:00 UTC, evgenyrodionov commented on src/Homes/Filters/DatePicker.js
> +  } else {
без else

2018-01-21 00:00 UTC, evgenyrodionov commented on src/Homes/Filters/DatePicker.js
> +    return from + " — " + to;
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

2018-01-21 00:00 UTC, evgenyrodionov commented on src/Homes/Filters/DatePicker.js
> +const formatDate = (date, selected, defaultText) => {
чем отличается от предыдущего? путаницу создаёт

2018-01-21 00:00 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +    this.setState(prevState => ({
когда я говорил про коллбек, я имел в виду второй параметр сетстейта — там выполнится функция после установки стейта

2018-01-21 00:00 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +    const matchXs = window.matchMedia("(max-width: 450px)").matches;
удобно каждый раз прописывать?

2018-01-21 00:00 UTC, evgenyrodionov commented on src/Homes/Filters/_datepicker.css
> +@media (max-width: 450px) {
я же сказал, что max-width не используем

2018-01-21 00:00 UTC, evgenyrodionov commented on src/Homes/Filters/index.js
> +  setOpened = (opened, callback) => {
а зачем ты кб передаешь?

2018-01-22 09:01 UTC, shmlkv commented
https://build-trhtsluamh.now.sh

2018-01-22 14:38 UTC, imevro requested changes

2018-01-22 14:38 UTC, evgenyrodionov commented on src/Homes/Filters/DatePicker.js
> +import { matchXs } from "../../helpers.js";
зачем указывать .джс?

2018-01-22 14:38 UTC, evgenyrodionov commented on src/Homes/Filters/DatePicker.js
> +const buttonText = (start, end, isSelected) => {
функции имеются глаголом, а если они что-то возвращают, то и префиксом `get*`

2018-01-22 14:38 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +        startDate: this.state.selectedStartDate,
нахуя ты в стейт кладешь то, что и так в нём?

2018-01-22 19:06 UTC, imevro approved these changes

2018-01-22 19:07 UTC, merged